version: "3.3"
services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html